# Generated by Django 4.2.4 on 2023-08-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozon_products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='date',
            field=models.DateTimeField(auto_now=True, help_text='Дата и время добавления либо последнего обновления записи', verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='products',
            name='link',
            field=models.CharField(max_length=250, unique=True, verbose_name='Ссылка'),
        ),
    ]
