# Generated by Django 4.2.4 on 2023-08-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozon_products', '0002_products_date_alter_products_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='code',
            field=models.IntegerField(default=1, unique=True, verbose_name='Код товара'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='link',
            field=models.CharField(max_length=350, unique=True, verbose_name='Ссылка'),
        ),
    ]
