# Generated by Django 4.2.4 on 2023-08-04 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozon_products', '0004_alter_products_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('-date',), 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.CharField(blank=True, max_length=3000, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='products',
            name='discount',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Скидка'),
        ),
        migrations.AddField(
            model_name='products',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка на фото'),
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена'),
        ),
    ]
